### ISSUE TITLE
Feature Set

### ISSUE THREAD

**Issue by FTFX** [AtomGH/Aurora#4]
- [ ] Pipeline tools library
- [ ] Global/Project-level assets library
- [ ] Project files viewer (P4/SMB)
- [ ] Task tracking
- [ ] Planning/Reference board
- [ ] Cloud rendering/Render farm dashboard
